### ISSUE TITLE
Dovetail the neck to the body.

### ISSUE THREAD

**Issue by jhertzberg** [matthova/hovalin-files#16]
Using a dovetail joint may reduce or eliminate the need for one or both rods.

**Comment by matthova** [comment]
Did it 👍

**Comment by jhertzberg** [comment]
Hey Matt,

It looks great, thanks! I'll try it after I build my corex/y with a larger
printbed. The v3 neck with adhesion pads is a little too large for my
UM:Original print bed.

Regards,
Jeff

Jeff Hertzberg
(H) 718-636-6747
(M) 347-678-0699
(E) jeff@hertzberg.info
